name: TIENDA DIANELITO - Deploy Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: npm install
      env:
        DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
        DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
        TEBEX_SECRET_KEY: ${{ secrets.TEBEX_SECRET_KEY }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
    
    - name: Run tests
      run: npm test
    
    - name: Deploy to server
      run: |
        scp -r . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/path/to/deploy
      env:
        DISCORD_CALLBACK_URL: ${{ secrets.DISCORD_CALLBACK_URL }}